version: '3'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: admin1
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432

  advert_display:
    build: advert_display/
    depends_on:
      - "postgres"
    ports:
      - 5000:5000

  advert_info:
    build: advert_info/
    depends_on:
      - "postgres"
    ports:
      - 5001:5001

  user_info:
    build: user_info/
    depends_on:
      - "postgres"
    ports:
      - 5002:5002

  all_stats:
    build: all_stats/
    depends_on:
      - "postgres"
    ports:
      - 5003:5003